**0.a Create a list of all prime numbers smaller than n**

In [1]:
n=18
prime_list=[]
for i in range(2, n):
    for j in range(2, i):
        if i%j==0:
            break
    else:
        prime_list.append(i)

            
prime_list

[2, 3, 5, 7, 11, 13, 17]

**0.b Find the greatest common divisor between two numbers**

In [2]:
n=5*3*3*2*7
m=3*2*7*11
print(m,n)
gcd=1
for i in reversed(range(1, min(m,n)+1)):
    if n%i==0 and m%i==0:
        gcd=i
        break
print(gcd)

462 630
42


**0.c Least common multiple of two numbers**

In [4]:
n=5*3*3*2*7
m=3*2*7*11
print(m,n)
lcm=1
for i in range(max(m,n),m*n+1):
    if i%n==0 and i%m==0:
        lcm=i
        break
print(lcm)
print(m*n/gcd)

462 630
6930
6930.0


**1- Make a two-player Rock-Paper-Scissors game. (Hint: Ask for player plays (using input),
compare them, print out a message of congratulations to the winner, and ask if the players want
to start a new game)**

Remember the rules:
Rock beats scissors
Scissors beats paper
Paper beats rock

In [4]:
## Solution
print('''Please pick one:
                rock
                scissors
                paper''')

Please pick one:
                rock
                scissors
                paper


In [7]:
while True:
    game_dict = {'rock': 1, 'scissors': 2, 'paper': 3}
    
    
    player_a = str('')
    while player_a not in game_dict.keys() :
        player_a = str(input("Player a, choose between rock,scissors,paper: "))
   

    player_b = str('')
    while player_b not in game_dict.keys() :
        player_b = str(input("Player b, choose between rock,scissors,paper: "))
        
        
    a = game_dict.get(player_a)
    b = game_dict.get(player_b)
    dif = a - b
    
    
    if dif in [-1, 2]:
        print('player a wins.')
        if str(input('Do you want to play another game, yes or no?\n')) == 'yes':
            continue
        else:
            print('game over.')
            break
            
            
    elif dif in [-2, 1]:
        print('player b wins.')
        if str(input('Do you want to play another game, yes or no?\n')) == 'yes':
            continue
        else:
            print('game over.')
            break
    else:
        print('Draw.Please continue.')
        print('')

Player a, choose between rock,scissors,paper: rock
Player b, choose between rock,scissors,paper: paper
player b wins.
Do you want to play another game, yes or no?
no
game over.


**2 Change the program above to give the winner after three rounds**

In [ ]:
pl_a_nr=0
pl_b_nr=0
while True:
    game_dict = {'rock': 1, 'scissors': 2, 'paper': 3}
    
    
    player_a = str('')
    while player_a not in game_dict.keys() :
        player_a = str(input("Player A, choose between rock,scissors,paper: "))
   

    player_b = str('')
    while player_b not in game_dict.keys() :
        player_b = str(input("Player B, choose between rock,scissors,paper: "))
        
        
    a = game_dict.get(player_a)
    b = game_dict.get(player_b)
    dif = a - b
    
    
    if dif in [-1, 2]:
        print('player A wins the round.')
        pl_a_nr+=1
            
            
    elif dif in [-2, 1]:
        print('player B wins the round.')
        pl_b_nr+=1
        
    else:
        print('Draw.Please continue.')
        print('')
    if pl_a_nr==3:
        print('Player A wins.')
        break
    if pl_b_nr==3:
        print('Player a wins.')
        break

In [2]:
['a','b','c','a'].count('a')

2

In [4]:
max([300,200,100])

300

**3 Change the program above in the case that there are n players, playing for k rounds. The winner(s) is the player with most points. A point is earned for every opponent you defeat.**

In [20]:
nr_players=7
nr_rounds=3
scores=[0]*nr_players
players_dict=dict([[i, 'player'+str(i+1)] for i in range(nr_players)])

for roundi in range(nr_rounds):
    game_dict = {'rock': 1, 'scissors': 2, 'paper': 3}
    choices=[]
    for player in range(nr_players):
        
        player_choice = str('')
        while player_choice not in game_dict.keys() :
            player_choice = str(input("Player "+str(player+1)+", choose between rock,scissors,paper: "))
        choices.append(player_choice)

    choices_dict={'rock': choices.count('rock'),'scissors': choices.count('scissors'),
                  'paper': choices.count('paper') }  
    beats_dict={'rock': 'scissors', 'paper': 'rock', 'scissors': 'paper'}
    #print(choices)
    #print(choices_dict)
    for player, choice in enumerate(choices):
        #print(beats_dict[choice])
        #print(choices_dict[beats_dict[choice]])
        scores[player]+=choices_dict[beats_dict[choice]]

    print(scores)    
    
m = max(scores)
winners=[i for i, j in enumerate(scores) if j == m]
print('The winners are: ')
for winner in winners:
    print(players_dict[winner], ',score: ', scores[winner])


Player 1, choose between rock,scissors,paper: paper
Player 2, choose between rock,scissors,paper: paper
Player 3, choose between rock,scissors,paper: paper
Player 4, choose between rock,scissors,paper: paper
Player 5, choose between rock,scissors,paper: rock
Player 6, choose between rock,scissors,paper: scissors
Player 7, choose between rock,scissors,paper: paper
[1, 1, 1, 1, 1, 5, 1]
Player 1, choose between rock,scissors,paper: scissors
Player 2, choose between rock,scissors,paper: paper
Player 3, choose between rock,scissors,paper: rock
Player 4, choose between rock,scissors,paper: rock
Player 5, choose between rock,scissors,paper: rock
Player 6, choose between rock,scissors,paper: rock
Player 7, choose between rock,scissors,paper: paper
[3, 5, 2, 2, 2, 6, 5]
Player 1, choose between rock,scissors,paper: scissors
Player 2, choose between rock,scissors,paper: scissors
Player 3, choose between rock,scissors,paper: scissors
Player 4, choose between rock,scissors,paper: rock
Player 5, c

**4- Build a game where you draw a series of random integers evenly
distributed from 0 and 10, with the aim of getting the sum as close as possible to 21, but not
larger than 21. You are out of the game if the sum passes 21. After each draw, you are told the
number and your total sum, and are asked whether you want another draw or not.**

In [3]:
from random import randint

upper_limit = 21
not_finished = True
sum_ = 0
while not_finished:
    next_number = randint(0, 10)
    print("You got: ", next_number)
    sum_ += next_number
    if sum_> upper_limit:
        print("Game over, you passed 21 (with your %d points)!"\
        % sum_)
        not_finished = False
    else:
        print("Your score is now: %d points!" % (sum_))
        answer = input('Another draw (y/n)? ')
        if answer != 'y':
            not_finished = False
        print("Finished!")

You got:  2
Your score is now: 2 points!
Another draw (y/n)? y
Finished!
You got:  4
Your score is now: 6 points!
Another draw (y/n)? y
Finished!
You got:  3
Your score is now: 9 points!
Another draw (y/n)? y
Finished!
You got:  4
Your score is now: 13 points!
Another draw (y/n)? y
Finished!
You got:  6
Your score is now: 19 points!
Another draw (y/n)? n
Finished!


**5 - Create a multiplayer version of the game above where the results of each player are saved
in a dictionary corresponding to the players' names, and announce the winners once each player has finished their turn. In case that they were all eliminated, label the winners but, also state that they all lost** 

In [13]:
from random import randint

nr_players=3
players_dict=dict([[i, 'player'+str(i+1)]for i in range(nr_players)])
scores=[]
eliminated=0
for player in range(nr_players):
    upper_limit = 21
    not_finished = True
    sum_ = 0
    while not_finished:
        next_number = randint(0, 10)
        print("You got: ", next_number)
        sum_ += next_number
        if sum_> upper_limit:
            print("Your turn is over, you passed 21 (with your %d points)!"\
            % sum_)
            if player<nr_players-1:
                print('\nThe turn of the next player')
            else:
                print('GAME OVER')
            sum_=-1
            eliminated+=1
            not_finished = False
        else:
            print("Your score is now: %d points!" % (sum_))
            answer = input('Another draw (y/n)? ')
            if answer != 'y':
                not_finished = False
                if player<nr_players-1:
                    print('\nThe turn of the next player')
                else:
                    print('GAME OVER')
                
    scores.append(sum_)
print(scores)
m = max(scores)
winners=[i for i, j in enumerate(scores) if j == m]
print('The winners are: ')
for winner in winners:
    print(players_dict[winner], ',score: ', scores[winner])

if eliminated==nr_players:
    print('...even though they all lost')

You got:  4
Your score is now: 4 points!
Another draw (y/n)? y
You got:  2
Your score is now: 6 points!
Another draw (y/n)? y
You got:  6
Your score is now: 12 points!
Another draw (y/n)? y
You got:  5
Your score is now: 17 points!
Another draw (y/n)? y
You got:  9
Your turn is over, you passed 21 (with your 26 points)!

The turn of the next player
You got:  3
Your score is now: 3 points!
Another draw (y/n)? y
You got:  8
Your score is now: 11 points!
Another draw (y/n)? y
You got:  5
Your score is now: 16 points!
Another draw (y/n)? y
You got:  3
Your score is now: 19 points!
Another draw (y/n)? y
You got:  1
Your score is now: 20 points!
Another draw (y/n)? y
You got:  0
Your score is now: 20 points!
Another draw (y/n)? y
You got:  5
Your turn is over, you passed 21 (with your 25 points)!

The turn of the next player
You got:  5
Your score is now: 5 points!
Another draw (y/n)? y
You got:  3
Your score is now: 8 points!
Another draw (y/n)? y
You got:  4
Your score is now: 12 points!
A

**6  Given two matrices the task is that we will have to create a program to multiply two matrices in
python.**

**6.1 : Using Simple Nested Loops to iterate through each row and each column.**

In [27]:
# Program to multiply two matrices using nested loops
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
[4, 5, 6],
[7, 8, 9]]
# take a 3x4 matrix
B = [[5, 8, 1, 2],
[6, 7, 3, 0],
[4, 5, 9, 1]]

In [28]:
result = np.zeros((len(A),len(B[0])))
# iterating by row of A
for i in range(len(A)):
    # iterating by coloum by B
    for j in range(len(B[0])):
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

In [30]:
for r in result:
    print(r)

[114. 160.  60.  27.]
[74. 97. 73. 14.]
[119. 157. 112.  23.]


**6.2 : Using list comprehension. (Hint : check zip)**

In [40]:
zip??

In [35]:
A = [[12, 7, 3],
[4, 5, 6],
[7, 8, 9]]
# take a 3x4 matrix
B = [[5, 8, 1, 2],
[6, 7, 3, 0],
[4, 5, 9, 1]]

In [39]:
[B_col for B_col in zip(*B)]

[(5, 6, 4), (8, 7, 5), (1, 3, 9), (2, 0, 1)]

In [33]:
result = [[sum(a * b for a, b in zip(A_row, B_col))
for B_col in zip(*B)]
for A_row in A]

In [34]:
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


**7- Take a name, for instance Harrison, and write a program that asks you to guess the name, and
gives you one letter of the name at each iteration (starting from the first letter).In addition keep
track of the number of guesses you had and print it at the end. Your program should stop if the
number of guesses is greater than the number of letters in the name.**

In [42]:
name = 'Harrison'
guess = input("So I'm thinking of person's name. Try to guess it: ")
pos = 0
while guess != name and pos < len(name):
    print("Nope, that's not it! Hint: letter ", end='')
    print(pos + 1, "is", name[pos] + ". ", end='')
    guess = input("Guess again: ")
    pos = pos + 1
if pos == len(name) and name != guess:
    print("Too bad, you couldn't get it. The name was", name + ".")
else:
    print("\nGreat, you got it in", pos + 1, "guesses!")


So I'm thinking of person's name. Try to guess it: Hendry
Nope, that's not it! Hint: letter 1 is H. Guess again: Harry
Nope, that's not it! Hint: letter 2 is a. Guess again: Hasky
Nope, that's not it! Hint: letter 3 is r. Guess again: Harriet
Nope, that's not it! Hint: letter 4 is r. Guess again: Harrison

Great, you got it in 5 guesses!
